//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsAccessLevels
    {
        public int accessLevelID { get; set; }
        public Nullable<int> userGroupID { get; set; }
        public string menuName { get; set; }
        public string menuItemName { get; set; }
        public Nullable<int> formID { get; set; }
        public Nullable<bool> canAdd { get; set; }
        public Nullable<bool> canView { get; set; }
        public Nullable<bool> canEdit { get; set; }
        public Nullable<bool> canDelete { get; set; }
        public Nullable<bool> canApprove { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdByID { get; set; }
        public string formName { get; set; }
        public string createdByName { get; set; }
        public string groupName { get; set; }
        public Nullable<System.Guid> sessionID { get; set; }
    }
}
