//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsCity
    {
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<int> modifiedByID { get; set; }
        public Nullable<int> createdByID { get; set; }
        public string userName { get; set; }
        public int cityID { get; set; }
        public string cityName { get; set; }
        public string cityCode { get; set; }
        public int stateID { get; set; }
        public string stateName { get; set; }
        public Nullable<System.Guid> sessionID { get; set; }
    }
}
