//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsMenus
    {
        public int menuID { get; set; }
        public string menuName { get; set; }
        public string menuDesc { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdByID { get; set; }
        public Nullable<int> menuRanking { get; set; }
        public Nullable<System.Guid> sessionID { get; set; }
    }
}
