//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsMenuItems
    {
        public int menuItemID { get; set; }
        public Nullable<int> menuID { get; set; }
        public string menuName { get; set; }
        public string menuItemName { get; set; }
        public string menuItemDescription { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdByID { get; set; }
        public string createdByName { get; set; }
        public Nullable<System.Guid> sessionID { get; set; }
        public Nullable<int> menuItemRanking { get; set; }
    }
}
