//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsMenuIcons
    {
        public int menuIconID { get; set; }
        public int menuID { get; set; }
        public string menuName { get; set; }
        public string menuIconName { get; set; }
    }
}
