//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsRegister
    {
        public int tdoRegisterID { get; set; }
        public string jobNumber { get; set; }
        public System.DateTime dateReceived { get; set; }
        public System.DateTime expiryDate { get; set; }
        public string status { get; set; }
        public int cargoTypeID { get; set; }
        public string cargoTypeName { get; set; }
        public string fileRef { get; set; }
        public Nullable<int> destinationID { get; set; }
        public string destinationName { get; set; }
        public Nullable<int> terminalID { get; set; }
        public string terminalName { get; set; }
        public string containerNo { get; set; }
        public Nullable<int> returnTerminal { get; set; }
        public string returnTerminalName { get; set; }
        public Nullable<int> truckID { get; set; }
        public string truckName { get; set; }
        public string truckRegNum { get; set; }
        public Nullable<System.DateTime> tdoReceiptDate { get; set; }
        public Nullable<System.DateTime> schDelDate { get; set; }
        public Nullable<System.DateTime> loadingTime { get; set; }
        public Nullable<System.DateTime> dispatchTime { get; set; }
        public string remarks { get; set; }
        public Nullable<int> createdByID { get; set; }
        public string userName { get; set; }
        public Nullable<System.Guid> sessionID { get; set; }
        public int stateID { get; set; }
        public string stateName { get; set; }
    }
}
