//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsTruck
    {
        public int truckID { get; set; }
        public string truckName { get; set; }
        public string regNumb { get; set; }
        public Nullable<int> truckTypeID { get; set; }
        public string truckTypeName { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<int> modifiedByID { get; set; }
        public Nullable<int> createdByID { get; set; }
        public Nullable<System.Guid> sessionID { get; set; }
        public string userName { get; set; }
    }
}
