//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsUserGroups
    {
        public int userGroupID { get; set; }
        public string groupName { get; set; }
        public string description { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<int> createdByID { get; set; }
        public string createdByName { get; set; }
        public System.Guid sessionID { get; set; }
    }
}
