//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsUsers
    {
        public int userID { get; set; }
        public int userGroupID { get; set; }
        public string groupName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public bool passwordCanExpire { get; set; }
        public Nullable<System.DateTime> passwordExpiryDate { get; set; }
        public bool isLocked { get; set; }
        public int loginAttempts { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public string theme { get; set; }
        public bool resetPassword { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<int> createdByID { get; set; }
        public System.Guid sessionID { get; set; }
    }
}
