//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForTraining.Database
{
    using System;
    
    public partial class ClsUploadRegister
    {
        public string jobNumber { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string status { get; set; }
        public string cargoType { get; set; }
        public string fileRef { get; set; }
        public string destination { get; set; }
        public string terminal { get; set; }
        public string containerNo { get; set; }
        public string returnTerminal { get; set; }
        public string truck { get; set; }
        public Nullable<System.DateTime> tdoReceiptDate { get; set; }
        public Nullable<System.DateTime> schDelDate { get; set; }
        public Nullable<System.DateTime> loadingTime { get; set; }
        public Nullable<System.DateTime> dispatchTime { get; set; }
        public string remarks { get; set; }
        public string response { get; set; }
        public Nullable<bool> isSuccess { get; set; }
    }
}
